services:
  - docker

branches:
  only:
    - master
      
script: 
  - docker build -t devgavrilov/coderunner-jobe-sharp-server .
  - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
  - docker push devgavrilov/coderunner-jobe-sharp-server